from SimpleCV import Image
import time
img = Image("/home/pi/Documents/JCLab_Research/Image_Test/testimage.png")
#img = img.binarize()
##img.show()
##time.sleep(5)
org_color = (255,153,0)
org_distance = img.colorDistance(org_color).invert()
img_blobs = org_distance.findBlobs()
img_blobs.draw(color=(0,0,0),width=3)
org_distance.save("/home/pi/Documents/JCLab_Research/Image_Test/testimage_org.png")
org_distance.show()
time.sleep(5)
img.addDrawingLayer(org_distance.dl())
img.save("/home/pi/Documents/JCLab_Research/Image_Test/testimage_dl.png")
img.show()
time.sleep(5)
#print "Areas: ",img_blobs.area()
#print "Angles: ",img_blobs.angle()
#print "Centers: ",img_blobs.coordinates()
